accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.TopPage.as_view(), name='top'),
    path('home/', views.Home.as_view(), name='home'),
    path('thanks/', views.Thanks.as_view(), name='thanks'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),  # contrib.auth使用
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),  # contrib.auth使用
    path('detail/<int:pk>/', views.UserDetail.as_view(), name='detail'),
    path('update/<int:pk>/', views.UserUpdate.as_view(), name='update'),
    path('googletrans/', views.googletrans, name='googletrans'),
    path('index/', views.MemberList.as_view(), name='index'),  # あとで修正必要
]

django_accounts/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path


urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=100, blank=True, null=True)
    password1 = models.CharField(max_length=256, blank=True, null=True)
    password2 = models.CharField(max_length=256, blank=True, null=True)
    phone = models.CharField(max_length=30, blank=True, null=True)

    # 翻訳用
    username_jp = models.CharField(max_length=100, blank=True, null=True)


    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    instance.userprofile.save()

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from accounts.models import UserProfile


# signup form
class UserCreateForm(UserCreationForm):
        username = forms.CharField(max_length=130, required=True , label="Username")
        password1 = forms.CharField(widget=forms.PasswordInput(),label="Password")
        password2 = forms.CharField(widget=forms.PasswordInput(),label="Password(Confirm)")
        phone = forms.CharField(max_length=30, required=True , label="Phone number")

        class Meta:
            model = User
            fields = ("username", "password1", "password2", "phone")


# eidt form TEST
class UserUpdateForm(forms.ModelForm):
    """ユーザー情報更新フォーム"""
    class Meta:
        model = UserProfile
        fields = ("password1", "password2", "phone")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

accounts/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect, get_object_or_404, resolve_url
from django.views import generic
from requests import request
from accounts.models import UserProfile
from .forms import UserCreateForm, UserUpdateForm
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import TemplateView
from googletrans import Translator
from django.views.generic.edit import UpdateView
from django.core.mail import send_mail



# ユーザーモデルセット
User = get_user_model()


class TopPage(TemplateView):
    """
    TOPページ
    """
    template_name = 'accounts/top.html'



class Thanks(TemplateView):
    """
    サンクスページ
    """
    template_name = 'accounts/thanks.html'



class Home(TemplateView):
    """
    HOMEページ
    """
    template_name = "accounts/home.html"


def signup(request):
    """
    ユーザー新規登録
    """
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.userprofile.username = form.cleaned_data.get('username')  # added
            user.userprofile.password1 = form.cleaned_data.get('password1')
            user.userprofile.password2 = form.cleaned_data.get('password2')
            user.userprofile.phone = form.cleaned_data.get('phone')
            user.save()
            password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=password)
            login(request, user)

            # Google翻訳
            user.refresh_from_db()
            translator = Translator()
            translated = translator.translate(user.userprofile.username, src='vi', dest='ja')
            user.userprofile.username_jp = translated.text

            # メール送信
            send_notification(user.userprofile.username,user.userprofile.phone)

            user.save()
            # d = {
            #     'text': translated_username.text
            # }
            # return render(request, 'accounts/googletrans.html', d) # 表示はせずデータベースに登録させる為グレーアウト

            return redirect('login')
    else:
        form = UserCreateForm()
    return render(request, 'accounts/signup.html', {'form': form})


def index(request):
    """
    ユーザー一覧表示
    """
    members = UserProfile.objects.all().order_by('id')
    return render(request, 'accounts/index.html', {'members':members})


#一覧（ページネーション用に追加）
from django.views.generic import ListView



#一覧表示（l)
class MemberList(ListView):
    model = UserProfile #利用するモデル
    context_object_name='members' #オブジェクト名の設定（標準ではobject_listとなってしまう）
    template_name='members/index.html' #テンプレートページの指定
    paginate_by = 1 #1ページあたりのページ数


# バリデーション・詳細表示・編集更新（テスト）https://narito.ninja/blog/detail/43/
class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser



class UserDetail(OnlyYouMixin, generic.DetailView):
    """
    ユーザー詳細表示
    """
    model = UserProfile
    template_name = 'accounts/detail.html'


class UserUpdate(OnlyYouMixin, generic.UpdateView):
    """
    ユーザー情報編集
    """
    model = UserProfile
    form_class = UserUpdateForm
    template_name = 'accounts/form.html'

    def get_success_url(self):
        return resolve_url('accounts:detail', pk=self.kwargs['pk'])



def delete(request, id):
    """
    ユーザー削除
    """
    # return HttpResponse("削除")
    member = get_object_or_404(UserProfile, pk=id)
    member.delete()
    return redirect('accounts:index')



def googletrans(request):
    """
    Googletrans翻訳  method
    """
    translator = Translator()
    translated = translator.translate('Bastian Schweinsteiger', src='de', dest='ja')
    d = {
        'text': translated.text
    }
    return render(request, 'accounts/googletrans.html',d)



class Googletrans(UpdateView):
    """
    Googletrans翻訳 class
    """
    model = UserProfile
    template_name = 'accounts/googletrans.html'
    fields = ["degree", "city", "state", "country", "age"]
    # success_url = reverse_lazy('accounts:home')
    def trans(self):
        translator = Translator()
        translated = translator.translate('Bastian Schweinsteiger', src='de', dest='ja')
        d = {
            'text': translated.text
        }
        return render(request, 'accounts/googletrans.html',d)



def send_notification(usernam,phone):
    """
    メール送信
    """
    subject = "SCS Reminde"
    message = "GOT A NEW STUDENT REGISTRTION!!\n\n\n\n" + "=================================================\n" + "・NAME:" + usernam + "\n\n" + "・PHONE: " + phone + "\n\n" + "=================================================\n" + "CALL TO HE/ER, BUY HOUSE!!!"
    from_email = 'toritoritorina@gmail.com'  # 送信者
    recipient_list = ["toritoritorina@gmail.com"]  # 宛先リスト
    send_mail(subject, message, from_email, recipient_list)

accounts/templates/accounts/detail.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% bootstrap_css %}
{# Load CSS and JavaScript #}
{% block breadcrumb %}
  <li class="breadcrumb-item active">Detail詳細</li>
{% endblock %}
{% block content %}
<div class="container">
    <h1 style="color:royalblue">ユーザー詳細情報</h1>
<table class="table">
    <tbody>
        <tr>
            <th>USER ID:</th>
            <td>{{ user.user_id }}</td>
        </tr>
        <tr>
            <th>USER NAME:</th>
            <td>{{ user.userprofile.username }}</td>
        </tr>
        <tr>
            <th>PASSWORD1:</th>
            <td>{{ user.userprofile.password1 }}</td>
        </tr>
        <tr>
            <th>PASSWORD2:</th>
            <td>{{ user.userprofile.password2 }}</td>
        </tr>
        <tr>
            <th>PASSWORD3:</th>
            <td>{{ user.userprofile.password3 }}</td>
        </tr>
        <tr>
            <th>PHONE:</th>
            <td>{{ user.userprofile.phone }}</td>
        </tr>
    </tbody>
</table>
{% endblock %}

accounts/templates/accounts/form.html
{% extends "base.html" %}
{% load static %}
{% block breadcrumb %}
  <li class="breadcrumb-item active">ユーザー情報編集form.html</li>
{% endblock %}
{% block content %}
<div class="container">
    <h1 style="color:royalblue">ユーザー情報編集</h1>
<p>以下よりユーザー情報編集を行って下さい。</p>
<form action="" method="POST">
    {{ form.non_field_errors }}
    <table class="table table-sm">
        <tbody>
        {% for field in form %}
            <tr>
                <th><label for="{{ field.id_for_label }}">{{ field.label }}</label></th>
                <td>{{ field }} {{ field.errors }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% csrf_token %}
    <button type="submit" class="btn btn-primary" >編集完了</button>
</form>
{% endblock %}

accounts/templates/accounts/googletrans.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% bootstrap_css %}
{# Load CSS and JavaScript #}
{% block breadcrumb %}
  <li class="breadcrumb-item active">Googletrans翻訳</li>
{% endblock %}
{% block content %}
<h1 style="color:royalblue">Googletrans翻訳テスト</h1>
    <div class="row">
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <h1>Here is your profile information(TRANSLATED)</h1>
                <ul>
                    <li>text:{{ text }}</li>
                </ul>
            {% else %}
                  <p>NOT LOGGED IN YET!</p>
            {% endif %}
        </ul>
    </div>
{% endblock %}

accounts/templates/accounts/home.html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-154721166-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-154721166-1');
</script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-154721166-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-154721166-1');
</script>





{% extends "base.html" %}
{% load bootstrap4 %}
{% bootstrap_css %}
{# Load CSS and JavaScript #}
{% block breadcrumb %}
  <li class="breadcrumb-item active">Homeホーム</li>
{% endblock %}
{% block content %}
<div class="row">
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
            <div class="user-info">
                <h1 style="color:royalblue">ユーザー情報</h1>
                <ul>
                    <li>User ID : {{ user.userprofile.user_id }}</li>
                    <li>First Name : {{ user.username }}</li>
                    <li>Password1 : {{ user.userprofile.password1 }}</li>
                    <li>Password2 : {{ user.userprofile.password2 }}</li>
                    <li>Phone : {{ user.userprofile.phone }}</li>
                </ul>
            </div>
        {% else %}
            <div class="instruction-msg">
              <h1 style="color:royalblue">HOME</h1>
              <h5>Wellcome to SCS-version3.03</h5>
              <h5>右上より新規登録またはログインを行ってください！</h5>
            </div>
        {% endif %}
    </ul>
</div>
{% endblock %}

accounts/templates/accounts/index.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% bootstrap_css %}
{# Load CSS and JavaScript #}
{% bootstrap_javascript %}
{% block breadcrumb %}
  <li class="breadcrumb-item active">Indexインデックス</li>
{% endblock %}

{% block title %}
一覧を表示する予定
{% endblock title %}

{% block content %}
<h3>一覧表示</h3>

<!--　修正必要 -->


<a href="{% url 'accounts:add' %}" class="btn btn-primary btn-sm">追加</a>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>氏名</th>
            <th>E-Mail</th>
            <th>年齢</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        {% for member in members %}
        <tr>
            <td>{{ user.userprofile.user_id }}</td>
            <td><a href="{% url 'accounts:detail' id=member.id %}">{{ user.userprofile.username }}</a></td>
            <td>{{ user.userprofile.password1 }}</td>
            <td>{{ user.userprofile.password2 }}</td>
            <td>{{ user.userprofile.password3 }}</td>
            <td>{{ user.userprofile.phone }}</td>
            <td>
                <a href="{% url 'accounts:edit' id=member.id %}" class="btn btn-primary btn-sm">編集</a>
                <a href="{% url 'accounts:delete' id=member.id %}" class="btn btn-primary btn-sm" id="btn_del">削除</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<!-- ページネーションをここに入れる -->

{% endblock content %}

<!-- jsを入れる -->
{% block script %}
{% endblock %}

accounts/templates/accounts/top.html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-154721166-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-154721166-1');
</script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-154721166-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-154721166-1');
</script>




{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TOP PAGE SCS-version3.03</title>
    <meta name="description" content="{% block description %}{% endblock %}">

    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
<body>
    <!-- ナビバー -->
    <div class="top">
        <nav class="navbar navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'accounts:home' %}"><img src="/static/img/logo.png" width="60" height="50" alt="" style="color:#fff; margin-right:15px;";>Kỹ năng lên tại Nhật Bản! Nhấn vào đây để đăng ký!日本でスキルアップしよう！登録はこちらから！</a>
            <ul class="nav nav-tabs justify-content-end">
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Đăng ký người dùng mới新規ユーザー登録</a></li>
            </ul>
        </nav>
    </div>

    <!-- メインコンテンツ（サイドバー＆データ） -->
    <div class="container-fluid">
        <div class="row">

                <img src="/static/img/photo1.jpg" style="width:100%;">
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <div class="col-md-12">
                    <ul class="nav nav-tabs justify-content-start">
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Đăng ký tại đây! !ここから登録しよう！！</a></li>
                    </ul>
                </div>

                <img src="/static/img/photo2.jpg" style="width:100%;">
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <div class="col-md-12">
                    <ul class="nav nav-tabs justify-content-start">
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Đăng ký tại đây! !ここから登録しよう！！</a></li>
                    </ul>
                </div>

                <img src="/static/img/photo3.jpg" style="width:100%;">
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <div class="col-md-12">
                    <ul class="nav nav-tabs justify-content-start">
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Đăng ký tại đây! !ここから登録しよう！！</a></li>
                    </ul>
                </div>

                <img src="/static/img/photo3.jpg" style="width:100%;">
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <div class="col-md-12">
                    <ul class="nav nav-tabs justify-content-start">
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Đăng ký tại đây! !ここから登録しよう！！</a></li>
                    </ul>
                </div>

                <img src="/static/img/photo4.jpg" style="width:100%;">
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <p>Duong san sẽ viết lên những bài báo rôm rả ở đây.Duong san sẽ viết lên những bài báo rôm rả ở đây..</p>
                <div class="col-md-12">
                    <ul class="nav nav-tabs justify-content-start">
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Đăng ký tại đây! !ここから登録しよう！！</a></li>
                    </ul>
                </div>

        </div>
    </div>

    <footer class="footer col-md-12">
        <div class="footer-text">
            <p style="font-size:150%;">GLC GROUP 国際関係投資株式会社</p>
            <p>教育施設：Viet Nam, Ha Noi市Nam Tu Liem郡My Dinh1区 Nguyen Co Thach通り68番号MD COMPLEXビル12A階<br>本社：Viet Nam, Ha Noi市Ha Dong郡Phuc La区Tan Xa,Xa La通り44番</p>
            <p>www.glc.org.vn / info@glc.org.vn</p>
            <p>©︎All rights are protected by GLC Corporation.</p>
        </div>
    </footer>

</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}SCS-version3.03{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}">

    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
<body>
    <!-- ナビバー -->
    <div class="top">
        <nav class="navbar navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'accounts:home' %}"><img src="/static/img/logo.png" width="60" height="50" alt="" style="color:#fff; margin-right:15px;";>SCS-Version3.03</a>
            <ul class="nav nav-tabs justify-content-end">
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:home' %}">HOME</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:detail' user.pk %}">ユーザー情報表示</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:update' user.pk %}">ユーザー情報編集</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:googletrans' %}">Google翻訳</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">ログアウト</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:home' %}">HOME</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">ログイン</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">新規ユーザー登録</a></li>
                {% endif %}
            </ul>
            <!-- disabled
            <form class="form-inline pull-xs-right">
                <input class="form-control" type="text" placeholder="Search">
                <button class="btn btn-success-outline" type="submit">Search</button>
            </form>
            disabled-->
        </nav>
    </div>

    <!-- メインコンテンツ（サイドバー＆データ） -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <div class="list-group">
                    <a href="#" class="list-group-item disabled" style="font-weight:bold; font-size:large;">GLC会社紹介</a>
                    <a href="#" class="list-group-item">1_1 : 公式PDF会社概要</a>
                    <a href="#" class="list-group-item">1_2 : 公式ホームページ</a>
                    <a href="#" class="list-group-item">1_3 : 住所マップ</a>
                </div>
                <div class="list-group">
                    <a href="#" class="list-group-item disabled" style="font-weight:bold; font-size:large;">TITP技能実習の流れ</a>
                    <a href="#" class="list-group-item">2_1 : TITPって何？</a>
                    <a href="#" class="list-group-item">2_2 : どの様な流れになるの？</a>
                    <a href="#" class="list-group-item">2_3 : 費用は？</a>
                    <a href="#" class="list-group-item">2_4 : 必要書類は？</a>
                </div>
                <div class="list-group">
                    <a href="#" class="list-group-item disabled" style="font-weight:bold; font-size:large;">（参考）</a>
                    <a href="#" class="list-group-item">3_1 : OTIT技能実習機構</a>
                    <a href="#" class="list-group-item">3_2 : JITCO</a>
                    <a href="#" class="list-group-item">3_3 : MOLISA</a>
                    <a href="#" class="list-group-item">3_4 : DOLAB</a>
                </div>
            </div>
            <div class="col-md-9">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

    <footer class="footer col-md-12">
        <div class="footer-text">
            <p style="font-size:150%;">GLC GROUP 国際関係投資株式会社</p>
            <p>教育施設：Viet Nam, Ha Noi市Nam Tu Liem郡My Dinh1区 Nguyen Co Thach通り68番号MD COMPLEXビル12A階<br>本社：Viet Nam, Ha Noi市Ha Dong郡Phuc La区Tan Xa,Xa La通り44番</p>
            <p>www.glc.org.vn / info@glc.org.vn</p>
            <p>©︎All rights are protected by GLC Corporation.</p>
        </div>
    </footer>



</body>
</html>